services:
  app:
    image: ${DOCKERHUB_IMAGE}:${GITHUB_SHA}
    container_name: verrify_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: ${PORT:-3000}
      DB_HOST: postgres
      DB_PORT: '5432'
      RABBITMQ_URI: amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      LOG_FILE_PATH: /logs
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - /home/verrify/logs:/logs
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - verrify_net
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget -q --spider http://localhost:3000/api/v1/health || exit 1',
        ]
      interval: 30s
      timeout: 5s
      start_period: 60s
      retries: 5

  postgres:
    image: postgis/postgis:18
    container_name: verrify_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - verrify_net
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"']
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management
    container_name: verrify_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - verrify_net
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'check_port_connectivity']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  verrify_net:
    driver: bridge
    name: verrify_net

volumes:
  postgres_data:
  rabbitmq_data:
