export enum AddressFileTypeEnum {
  UTILITY_BILL = 'UTILITY_BILL',
  VOTER_CARD = 'VOTER_CARD',
  BANK_STATEMENT = 'BANK_STATEMENT',
  LEASE_AGREEMENT = 'LEASE_AGREEMENT',
  DRIVER_LICENSE = 'DRIVER_LICENSE',
}
