export enum EmailType {
  EMAILVERIFICATION = 'EMAIL_VERIFICATION',
  ACCOUNTVERIFICATION = 'ACCOUNT_VERIFICATION',
  ACCOUNTREGISTRATION = 'ACCOUNT_REGISTRATION',
  PASSWORDRESET = 'PASSWORD_RESET',
}
