export enum EmailType {
  EMAILVERIFICATION = 'EMAIL_VERIFICATION',
  ACCOUNTVERIFICATION = 'ACCOUNT_VERIFICATION',
  ACCOUNTREGISTRATION = 'ACCOUNT_REGISTRATION',
  PASSWORDRESET = 'PASSWORD_RESET',
  CONTACTMEREPLY = 'CONTACTMEREPLY',
  ADMINCONTACTMEREPLY = 'ADMINCONTACTMEREPLY',
  COMPANY_VERIFIED = 'COMPANY_VERIFIED',
  COMPANY_REJECTED = 'COMPANY_REJECTED',
  PROPERTY_VERIFIED = 'PROPERTY_VERIFIED',
  PROPERTY_REJECTED = 'PROPERTY_REJECTED',
}
