export enum FileType {
  PROFILE_PICTURE = 'PROFILE_PICTURE',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  COMPANY_PROFILE_PICTURE = 'COMPANY_PROFILE_PICTURE',
  CERTIFICATE_OF_OCCUPANCY = 'CERTIFICATE_OF_OCCUPANCY',
  CONTRACT_OF_SALE = 'CONTRACT_OF_SALE',
  SURVEY_PLAN = 'SURVEY_PLAN',
  LETTER_OF_INTENT = 'LETTER_OF_INTENT',
  DEED_OF_CONVEYANCE = 'DEED_OF_CONVEYANCE',
  ARTICLE_TITLE_IMAGE = 'ARTICLE_TITLE_IMAGE',
}
